### ISSUE TITLE
Recipes in Requirements File

### ISSUE THREAD

**Issue by jonathonl** [pfultz2/cget#33]
Recipes installed in a requirements file are not immediately available. The following requirements file needs to be ran twice to work. 
```
pfultz2/cget-recipes
xz
```

**Comment by pfultz2** [comment]
In general, its not good practice to include the recipes in the requirements file, because a user may want to use a different set of recipes to install the dependencies. Its similar to installing repository with apt-get. However, I understand the desire to want to do that as it makes it easy for a single cget command to build and install everything. 

Even still, installing from a file with `cget install --file requirements.txt` should work with recipes. So I need to fix that. Thanks for the report.

**Comment by pfultz2** [comment]
So I've merged a fix for this on master.
