### ISSUE TITLE
requirements not installed on windows

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [pfultz2/cget#38]
First, this project looks awesome.

I ran `cget install google/googletest`. Everything went fine.

But then I tried to start an empty folder and I wrote a `requirements.txt` containing only the line  `google/googletest`. Then I ran `cget install` on the command line and nothing happened.

I am on Windows 10. Am I missing something?

**Comment by pfultz2** [comment]
> First, this project looks awesome.

Thanks.

> Then I ran cget install on the command line and nothing happened.

You need to pass a [package source](http://cget.readthedocs.io/en/latest/src/package_src.html) to the install command. I probably should add a message that no package source was specified. 

The package source can be the directory where the `requirements.txt` file is(on windows you can't do `cget install .` so you need to be in another directory). Also, since you are missing a cmake file, you should use the `-X binary` flag, which will provide a default cmake file:

```
cget install -X binary <directory-with-requirements>
```

Also, the `cget build` command doesn't need a source directory, it will default to the current working directory. However, a cmake file is required.

You can also install the file directly instead of using a separate directory:

```
cget install -f requirements.txt
```

**Comment by usernameiwantedwasalreadytaken** [comment]
All right. I missed the reference to [`Directory`](http://cget.readthedocs.io/en/latest/src/package_src.html#directory) in the documentation.

`cget install -f requirements.txt` worked like a charm.

Again, thank you.
